### ISSUE TITLE
Utilities to fetch words from the page images using the roi's in the svg

### ISSUE THREAD

**Issue by fmeyenhofer** [dwettstein/pattern-recognition-2016#8]
parse the svg
utilities to fetch a word from the page image
binarize
crop
...

**Comment by jungomi** [comment]
0238f889e404d38676dd59f5ef500931f07d3982

Skew correction needs to be improved, [Skimage Hough Transformation](http://scikit-image.org/docs/dev/auto_examples/plot_line_hough_transform.html) looks good.
